# Automatically added by GitHub Actions on 2023-03-17 00:19:36.017081

channels:
- conda-forge
dependencies:
- p7zip
- pandas
- pygraphviz
- python=3.9
- r-base
- r-base=4.0.3
- r-irkernel
- scikit-learn
- tree
# needed to run one of sklearn-evaluation examples
- lxml
- pip:
  - ploomber>=0.21
  - ipywidgets<8
  - joblib
  - jupyter
  - matplotlib
  - mlflow
  - nbgitpuller
  - numpy
  - pandas
  - pandas-profiling
  - patool
  - plotly
  - pyarrow
  - pyunpack
  - scikit-learn
  - seaborn
  - sklearn-evaluation
  - soopervisor
  - soorgeon
  - sqlalchemy
  # jupysql examples
  - jupysql
  - duckdb
  - duckdb-engine
  - psutil
  - memory-profiler
  - debuglater[all]
name: projects