#!/bin/bash

# we need to run a few things that are in the projects repository
git clone https://github.com/ploomber/projects
cd projects/
pip install invoke
invoke setup --no-create-conda
rm -rf projects

# required to make nbgitpuller work
jupyter serverextension enable --py nbgitpuller --sys-prefix